name: Daily Visit Tennis Page

on:
  schedule:
    - cron: '0 23 * * *'   # 每天 UTC 23点，即东京时间8点
  workflow_dispatch:

jobs:
  visit-tennis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright
        run: npm install -D playwright

      - name: Run Playwright script
        run: |
          npx playwright install
          npx playwright codegen https://checkoutreact.top/#/searchTennis --save-storage=storage.json --timeout=10000
